// Generated by CoffeeScript 1.6.3
var Popover;

Popover = (function() {
  function Popover(opts) {
    var coords, div;
    div = document.createElement('div');
    div.setAttribute('class', 'bo-popover');
    switch (opts.position) {
      case 'selection':
        coords = this._getSelectionCoords();
        div.setAttribute('style', "position: absolute;                                            left: " + coords.x + "px;                                            top: " + coords.y + "px;                                           height: 50px;                                           width: 50px;                                           background-color: red;");
    }
    document.body.appendChild(div);
  }

  Popover.prototype._getSelectionElement = function() {
    var sel;
    sel = document.selection;
    if (!sel) {
      sel = window.getSelection();
    }
    return sel.anchorNode.parentElement;
  };

  Popover.prototype._getCoordsRelativeToElement = function(element, coords) {};

  Popover.prototype._getSelectionCoords = function () {
        var sel = document.selection, range;
        var x = 0, y = 0;
        if (sel) {
            if (sel.type != "Control") {
                range = sel.createRange();
                var rect = range.getClientRects()[0];
                console.log("rect: ")
                console.log(rect)
                /*range.collapse(true);*/

                x = range.boundingLeft + (rect.width / 2);
                y = range.boundingTop;
            }
        } else if (window.getSelection) {
            sel = window.getSelection();
            if (sel.rangeCount) {
                range = sel.getRangeAt(0).cloneRange();
                if (range.getClientRects) {
                    var rect = range.getClientRects()[0];
                    console.log("rect: ")
                    console.log(rect)
                    /*range.collapse(true);*/

                    x = rect.left + (rect.width / 2);
                    y = rect.top;
                }
            }
        }
        return { x: x, y: y };
    };

  return Popover;

})();
