// Generated by CoffeeScript 1.7.1
(function($) {
  var publish, remove, share, submit, _pid, _rvt;
  _rvt = $('article.content input[name="__RequestVerificationToken"]').val();
  _pid = parseInt($('article.content').data('post-id'), 10);
  publish = function() {
    return $.ajax("/post/" + _pid + "/publish", {
      type: 'POST',
      data: {
        __RequestVerificationToken: _rvt
      },
      error: function(jqxhr, status, error) {
        console.log(error);
        console.log(status);
        return console.log(jqxhr);
      },
      success: function(data, status, jqxhr) {
        return console.log('publish succeeded');
      }
    });
  };
  submit = function() {
    return console.log('submit');
  };
  share = function() {
    return console.log('share');
  };
  remove = function() {
    return console.log('delete');
  };
  $('button.publish').on('click', function(e) {
    return publish();
  });
  $('button.submit').on('click', function(e) {
    return submit();
  });
  $('button.share').on('click', function(e) {
    return share();
  });
  return $('button.delete').on('click', function(e) {
    return remove();
  });
})(jQuery);
