// Generated by CoffeeScript 1.7.1
(function($) {
  return $('.profile').on('click', function(e) {
    var $topbar, targetMargin;
    $topbar = $('.top-bar');
    targetMargin = (function() {
      switch (false) {
        case !((parseInt($topbar.css('margin-top'))) < 0):
          return 0;
        default:
          return -$topbar.height();
      }
    })();
    return $topbar.animate({
      "margin-top": targetMargin
    });
  });
})(jQuery);
