// Generated by CoffeeScript 1.6.3
var XMedium;

XMedium = (function() {
  function XMedium() {}

  XMedium.modifiers = {
    linkify: function(e) {
      var eventFilter, eventHandler, pop;
      eventFilter = function(e) {
        return ((e.key != null) && e.key === 'enter') || ((e.which != null) && e.which === 13);
      };
      eventHandler = function(e) {
        return document.execCommand('createLink', false, e.target.value);
      };
      return pop = new Popover({
        position: 'selection',
        content: "<input type=\"url\" size=\"35\" autofocus=\"true\" placeholder=\"paste or type a link\"/>",
        eventing: [
          {
            selector: 'input',
            event: 'keyup',
            filter: eventFilter,
            handler: eventHandler
          }
        ]
      });
    }
  };

  return XMedium;

})();
